# Generated by Django 4.2 on 2023-05-05 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0006_alter_unemployed_options_unemployed_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('pip_v', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('truvalist', models.IntegerField(verbose_name='Тривалість')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('adress', models.CharField(max_length=100, verbose_name='Адреса')),
                ('vartist', models.IntegerField(verbose_name='Вартість')),
                ('pr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vacancies.profession', verbose_name='Вид_послуг')),
            ],
        ),
    ]
