# Generated by Django 4.2 on 2023-05-07 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0007_cursu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursu',
            options={'ordering': ['-time_create'], 'verbose_name': 'Курси', 'verbose_name_plural': 'Курси'},
        ),
        migrations.AddField(
            model_name='cursu',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата опублікування'),
        ),
        migrations.AlterField(
            model_name='cursu',
            name='adress',
            field=models.CharField(max_length=100, null=True, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='cursu',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='cursu',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='cursu',
            name='pip_v',
            field=models.CharField(max_length=100, null=True, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='cursu',
            name='pr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vacancies.profession', verbose_name='Вид_послуг'),
        ),
        migrations.AlterField(
            model_name='cursu',
            name='truvalist',
            field=models.IntegerField(null=True, verbose_name='Тривалість'),
        ),
        migrations.AlterField(
            model_name='cursu',
            name='vartist',
            field=models.IntegerField(null=True, verbose_name='Вартість'),
        ),
        migrations.AlterField(
            model_name='unemployed',
            name='city',
            field=models.CharField(max_length=100, null=True, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='unemployed',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name='unemployed',
            name='nomer_phone',
            field=models.CharField(max_length=10, null=True, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='unemployed',
            name='pobat',
            field=models.CharField(max_length=100, null=True, verbose_name='По батькові'),
        ),
        migrations.AlterField(
            model_name='unemployed',
            name='priz',
            field=models.CharField(max_length=100, null=True, verbose_name='Прізвище'),
        ),
        migrations.AlterField(
            model_name='unemployed',
            name='special',
            field=models.CharField(max_length=100, null=True, verbose_name='Спеціальність'),
        ),
        migrations.AlterField(
            model_name='unemployed',
            name='street',
            field=models.CharField(max_length=50, null=True, verbose_name='Вулиця'),
        ),
        migrations.AlterField(
            model_name='unemployed',
            name='year',
            field=models.IntegerField(null=True, verbose_name='Вік'),
        ),
    ]
