# Generated by Django 4.2 on 2023-05-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0008_alter_cursu_options_cursu_time_create_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Вид послуг')),
            ],
            options={
                'verbose_name': 'Вид послуг',
                'verbose_name_plural': 'Вид послуг',
                'ordering': ['id'],
            },
        ),
    ]
