# Generated by Django 4.2 on 2023-05-08 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0009_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursu',
            name='pr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vacancies.category', verbose_name='Вид_послуг'),
        ),
    ]
