# Generated by Django 4.2 on 2023-05-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0011_unemployed_rez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unemployed',
            name='rez',
            field=models.BinaryField(null=True, verbose_name='Резюме'),
        ),
    ]
