# Generated by Django 4.2 on 2023-05-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0012_alter_unemployed_rez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unemployed',
            name='rez',
            field=models.FileField(null=True, upload_to='', verbose_name='Резюме'),
        ),
    ]
