# Generated by Django 4.2 on 2023-05-13 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0013_alter_unemployed_rez'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unemployed',
            name='nomer_phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефону повинен бути в форматі: '0XXXXXXXXX'. 10 цифр.", regex='^0\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='unemployed',
            name='rez',
            field=models.FileField(null=True, upload_to='files/', verbose_name='Резюме'),
        ),
    ]
