# Generated by Django 4.2 on 2023-05-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0014_alter_unemployed_nomer_phone_alter_unemployed_rez'),
    ]

    operations = [
        migrations.AddField(
            model_name='unemployed',
            name='kor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
