# Generated by Django 4.2 on 2023-05-18 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0015_unemployed_kor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='kilkbez',
            field=models.IntegerField(null=True, verbose_name='Кількість претендентів на вакансію'),
        ),
        migrations.AlterField(
            model_name='unemployed',
            name='kor',
            field=models.CharField(max_length=100, null=True, verbose_name='Користувач'),
        ),
    ]
