# Generated by Django 4.2 on 2023-05-18 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0016_vacancies_kilkbez_alter_unemployed_kor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursu',
            name='nomer_phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефону повинен бути в форматі: '0XXXXXXXXX'. 10 цифр.", regex='^0\\d{9}$')], verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='unemployed',
            name='nomer_phone',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message="Номер телефону повинен бути в форматі: '0XXXXXXXXX'. 10 цифр.", regex='^0\\d{9}$')], verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='vacancies',
            name='kilkbez',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кількість претендентів на вакансію'),
        ),
    ]
